name: rapidast-results-parser
run-name: Results parser
on:
  #schedule:
     #- cron: '30 5 * * *'
  workflow_dispatch:
jobs:
  parse-results:
    runs-on: ubuntu-latest
    steps:
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: checkout repo
        uses: actions/checkout@v4
        with: 
          token: ${{secrets.GH_TOKEN}}
      - name: Parse RapiDast results
        run: |
              curl -LJO https://raw.githubusercontent.com/jperezdealgaba/rapidast-results-parser/main/rapidast_parser.py
              python3 rapidast_parser.py --file zap_results/zap_analysis.json
            
      - name: Commit changes 
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add results/
          git commit -m "Updated parsed rapidast results"
          git push
